site_name: pymultitaper
docs_dir: mkdocs_docs
theme:
    name: "material"

plugins:
    - mkdocstrings
nav:
    - Quickstart: index.md
    - API Reference: api.md
markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
