[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pymultitaper"
version = "2.1.0rc1"
authors = [{ name = "Chao Kong", email = "kongchao1998@gmail.com" }]
description = "Fast easy-to-use multitaper spectrogram and spectrum calculation with Python"
readme = "README.md"
requires-python = ">=3.6"
dependencies = ["numpy", "scipy", "matplotlib"]

[project.urls]
Documentation = "https://fncokg.github.io/pymultitaper/"
Repository = "https://github.com/fncokg/pymultitaper/"
"Bug Tracker" = "https://github.com/fncokg/pymultitaper/issues"
